#!/bin/bash
set -e
echo "This is not needed. Everthing is done in docker-entrypoint.sh"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$POSTGRESQL_USER" WITH PASSWORD '$POSTGRESQL_PASSWORD';
	ALTER DATABASE "$POSTGRES_DB_1" OWNER TO $POSTGRESQL_USER;
	ALTER DATABASE "$POSTGRES_DB_2" OWNER TO $POSTGRESQL_USER;
	ALTER DATABASE "$POSTGRES_DB_3" OWNER TO $POSTGRESQL_USER;
EOSQL
